### ISSUE TITLE
Unsupported query types are being parsed as A records

### ISSUE THREAD

**Issue by rushmorem** [tailhook/dns-parser#18]
Any unknown query types are being parsed as A records. For example `dig -t GARBAGE` is parsed as a request for an A record.

**Comment by tailhook** [comment]
Query type is parsed [here](https://github.com/tailhook/dns-parser/blob/master/src/enums.rs#L200) and there is an explicit error case when type is wrong.

So, I guess it's a dig issue. I don't have much time to debug dig right now, but if you provide more info: the packet data that you are trying to parse of if you try to write a test for that case (they are not hard to write if you have data, just tests section at `parser.rs`), I may be able to address this issue faster.

**Comment by rushmorem** [comment]
You are right. The question is being sent as a request for an A record.
