### ISSUE TITLE
TXT: there can't be multiple chunks in a single RDATA field

### ISSUE THREAD

**Issue by rushmorem** [tailhook/dns-parser#24]
@tailhook in https://github.com/tailhook/dns-parser/pull/23#discussion_r147004945:

> As far as I understand there can't be multiple chunks in a single RDATA field.
>
> There can be multiple ResourceRecords though, and when there are multiple the app should consider them as a single concatenated resource record.
>
> Since generally, we don't try to join answers we should return a borrowed slice and remove all the concatenation code as far as I understand.

Putting this here so it doesn't get lost.

**Comment by tailhook** [comment]
Fixed in #31
