### ISSUE TITLE
This is great!

### ISSUE THREAD

**Issue by detro** [tailhook/dns-parser#36]
Hello,

I have been working on a DNS over HTTPS proxy DNS server, as an excuse to learn Rust: https://github.com/detro/mooncell. Because I did not want to engage in solving too many problems at once, given my Rust newbie-ness, I decided to leverage https://github.com/bluejekyll/trust-dns. Unfortunately this has turned out to be a really bad call, as the mix of Tokio, Hyper and Trust-DNS isn't really working. Especially because Trust-DNS has some design issues that don't make it easy to leverage some of it's parts.

So I have built the whole DoH-over-HTTPS part, but I'm now trying to build a simple enough solution to receive DNS queries (both TCP and UDP) and send back a response.

This project seems ideal, as it has a very limited amount of dependencies and it focuses exclusively on DNS Packet parsing.

Can I ask what are you planning to use this for? Just "professional" curiosity...

Thanks again for this

**Comment by tailhook** [comment]
It worked for `rotor-dns` in good old days :) Later I wanted to make similar thing for tokio/abstract-ns (i.e. a simple resolver for the case one doesn't need full power of trust-dns), but didn't have time to do it yet.

Also, there is a [sniffer](https://crates.io/crates/sniffglue) that uses dns-parser for parsing dns packets (Which I'm not affiliated with).

**Comment by detro** [comment]
I will give your crate a go: the interface looks very clean and simple, just the way I like it :)

Thanks a lot for this.
And let me know if there are areas that need extension as I'd be happy to submit PRs... eventually (my Rust is still not where I want it to be).

**Comment by tailhook** [comment]
> And let me know if there are areas that need extension

Well, unfortunately, there are lots of them. For example, the library has builtin limit of 512 bytes per packet for constructing packets. This doesn't make sense for DNS over TCP or HTTP. 

Anyway, feel free to send PRs for issues you'll hit when trying (like the above).
